lower_overview: demo_analysis/static/overviews/de_train_lower.png
nearest_threshold: 300
overview: demo_analysis/static/overviews/de_train.png
polygons_cn: []
polygons_en: []
transform:
  pzero:
  - -2308
  - 2078
  scale: 4.082077
