lower_overview: demo_analysis/static/overviews/de_vertigo_lower.png
nearest_threshold: 300
overview: demo_analysis/static/overviews/de_vertigo.png
polygons_cn: []
polygons_en: []
transform:
  pzero:
  - -3168
  - 1762
  scale: 4
