task: nxt_death
n_maps: 8
n_weapons: 51
n_projectiles: 2
T_Size: 32
Space_Size: 31
d: 256
d_inventory_embedding: 64
d_map_embedding: 32
d_projectile_embedding: 32
d_index_embedding: 32
space_transformer:
  layers: 8
  d_model: 256
  n_heads: 8
  ffn_dim: 1536
  dropout: 0.1
MLP:
  layers: 3
  hidden_dim: 256
Prediction_head:
  layers: 2
  hidden_dim: 256
Training:
  batch_size: 256
  num_workers: 4
  epochs: 10
  lr: 0.0002
  test_interval: 4096
  max_grad_norm: 1.0
  train_samples: 2770707
  test_samples: 26167
  warm_up_ratio: 0.1
  min_lr: 1.0e-05
calibration:
  temperature_scaling:
    temperature: 1.4939945936203003
